# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				arrow = true
				trader_llama = true
				donkey = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				iron_golem = true
				bat = true
				area_effect_cloud = true
				blaze = true
				cat = true
				zombie = true
				firework_rocket = true
				armor_stand = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				potion = true
				villager = true
				wandering_trader = true
				zombie_villager = true
				boat = true
				horse = true
				phantom = true
				cave_spider = true
				witch = true
				glow_squid = true
				cod = true
				glow_item_frame = false
				spider = true
				creeper = true
				enderman = true

